#
# Module manifest for module 'PS-SentinelOne'
# Generated by: davidhowell.tx
# Generated on: 2/22/2020
#

@{
	RootModule = 'PS-SentinelOne.psm1'
	ModuleVersion = '2.1.4'
	GUID = '77c92a6d-a1d2-4f37-aa01-10f2be735d0b'
	Author = 'davidhowell.tx'
	CompanyName = 'David Howell'
	Copyright = '(c) 2020 davidhowell.tx. All rights reserved.'
	Description = 'A PowerShell script module that provides command-line interaction and automation for the SentinelOne API.'

	FunctionsToExport = '*'
	CmdletsToExport = @()
	VariablesToExport = '*'
	AliasesToExport = @()

	PrivateData = @{
		PSData = @{

			# Tags applied to this module. These help with module discovery in online galleries.
			# Tags = @()

			# A URL to the license for this module.
			# LicenseUri = ''

			# A URL to the main website for this project.
			# ProjectUri = ''

			# A URL to an icon representing this module.
			# IconUri = ''

			# ReleaseNotes of this module
			# ReleaseNotes = ''

			Prerelease = ''

		} # End of PSData hashtable

	} # End of PrivateData hashtable

}
